## 1. Create a null vector of size 10 but the fifth value which is 1

In [26]:
import numpy as np

#initializing vector using zeros
null_vector = np.zeros(10,dtype = int)
#changing 5th element
null_vector[4] = 1
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


### Alternative solution

In [19]:
# gives an array of all False values except for one True at position 4.
vect = np.arange(10) == 4
null_vect = vect*(1)
print(null_vect)

[0 0 0 0 1 0 0 0 0 0]


## 2. Create a vector with values ranging from 10 to 49.

In [25]:
vector_1 = np.arange(10,50)
print(vector_1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
matrix = np.arange(9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [65]:
arr = np.array([1,2,0,0,4,0])
out_arr = np.nonzero(arr)
print ("Indices of non zero elements are\n%s\n"%(out_arr[0])) 

Indices of non zero elements are
[0 1 4]



## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [66]:
np.random.seed(8)
mat = np.random.randint(1,100,(10,10))
#print(mat)
print('Maximum value of array is\n%s\n'%(mat.max()))
print('Minimum value of array is\n%s\n'%(mat.min()))

Maximum value of array is
99

Minimum value of array is
3



## 6. Create a random vector of size 30 and find the mean value.

In [67]:
np.random.seed(5)
random_vector = np.random.randint(1,100,(1,30))
print('Random vector of size 30 is \n%s\n'%random_vector)
print('Mean of random vector is\n%s\n'%(random_vector.mean()))

Random vector of size 30 is 
[[79 62 17 74  9 63 28 31 81  8 77 16 54 81 28 45 78 76 66 48 31 85 87 19
  10 42 63  2 83 17]]

Mean of random vector is
48.666666666666664

